version: "3.8"

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    # command:
    #   - /bin/bash
    #   - -c
    #   - uvicorn backend.main:app --workers 1 --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: psql_user
      POSTGRES_PASSWORD: psql_password
    ports:
      - "5432:5432"
